### ISSUE TITLE
Video container shifted when "Download" is clicked

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5686] opened 2021-03-16 11:24 UTC
- `yarn dev` pointing to `v0.50.0-rc.1`
- Open dev tools and drag to roughly the width shown in the screenshot.
- When I click "Download", the video container shifted.

![image](https://user-images.githubusercontent.com/64950861/111301194-de6a8b80-868c-11eb-9efd-10a025a90c0a.png)

**Comment by lousando** [comment] 2021-04-07 02:36
This ticket can be closed as this issue was fixed by 21ad5077f7e105ee734d5203e1bf1cfec13842c3.

I can't comment on #5733 though as I am unable to reproduce that issue even before 21ad5077f7e105ee734d5203e1bf1cfec13842c3.

**Closed** 2021-04-09 13:54 UTC
Labels: type: bug
