### ISSUE TITLE
LBRY crashes to desktop when trying to upload on Windows 7 starting at v0.5.36

### ISSUE THREAD

**Issue by Sessh22** [lbryio/lbry-desktop#7732] opened 2022-11-12 19:36 UTC
Basically, when trying to upload a file at the upload screen, either using the Browse button to select a file via explorer or using drag-n-drop on the file results in the app crashing to desktop. This doesn't happen on 0.5.35, but does on 0.5.36 and 0.5.37.

To repro:

- go to your uploads and click the "Upload" button
- click "Browse" in the file box and select a file or drag and drop a file to upload
- app crashes a few seconds later

Of course, expected behavior is the file is accepted and the app functions normally.

- LBRY Daemon version: 0.110.0
- LBRY App version: 0.5.36 / 0.5.37
- LBRY Installation ID: 6MWuUBTneBsyYMS4VJtwNyU3KWX6mT5oEoUJGMoxg4gprTjGN3DkeWGMiHWVFiCUhP
- Operating system: Windows 7 SP1

I do see that in 0.5.36, there's an entry for "fixed various upload bugs including transcoding" which might be significant.

**Comment by IceGuye** [comment] 2022-11-13 12:02
I have the same issue in Linux (Fedora 37) . This bug happens when the file is large. Even with smaller file, such as a few mb short video, you can clearly feel that the lbry-desktop app is freezing for a few seconds.

**Comment by jessopb** [comment] 2022-11-14 14:24
Can you specify:
1) whether you're checking transcoding
2) whether size/format of file
3) whether you have "preview" enabled so you see the confirm/upload modal?

**Comment by Sessh22** [comment] 2022-11-14 15:05
1. Not using transcoding
2. 720p MP4 (h.264) / files are large between 500MB - 1GB and are 4+ hours long. Weekly uploader.
3. I do see the preview/confirm upload screen

**Comment by jessopb** [comment] 2022-11-14 15:44
Looks like disk usage spikes to 100% on file select. Looking into it.

**Comment by IceGuye** [comment] 2022-11-14 20:35
1. Not checking the transcoding.
2. 1 to 1.5 GB, 1 to 1.5 hours long, formats are MP4 H.264, WEBM VP9 (both crashed).
3. I have "preview enabled", but different from Sessh22, I can't even see the preview window. Right after selecting the file, the app would freeze and then crash in seconds. I can't even click the submit button.

**Comment by Sessh22** [comment] 2022-11-14 21:03
Perhaps I misunderstood. I have the preview enabled, but I get nowhere near being able to see it because as already stated, the app crashes a few seconds after selecting the file to upload. I thought he was asking if I had it enabled at all. I figured it was already assumed I wasn't actually seeing it because the app crashed almost immediately after selecting the file. Sorry for the confusion.

**Comment by jessopb** [comment] 2022-11-15 14:20
I've reproduced the problem. It is described in the limitations section of this link:
https://www.npmjs.com/package/get-file-object-from-local-path
I'll have a fix out today or tomorrow. The disk usage spikes were not the problem - that was my old windows vm.

**Comment by Sessh22** [comment] 2022-11-15 15:52
Great I'll be sure to test that out when it's available.

**Comment by jessopb** [comment] 2022-11-17 19:08
The alpha release with the fix is in releases now!

**Comment by Sessh22** [comment] 2022-11-17 20:55
I grabbed it and it now lets me select a file and everything appears to be normal. I can get to the preview screen now and did everything except push it through. Looks good!

**Comment by IceGuye** [comment] 2022-11-18 00:17
Tested on the last git pull. I can upload in Linux now.

**Comment by jessopb** [comment] 2022-11-18 14:19
yay!

**Closed by jessopb** 2022-11-18 14:19 UTC
Labels: type: bug
