### ISSUE TITLE
Found a claim that crashes the app and lbry.tv

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3231] opened 2019-11-16 01:06 UTC
Probably worth checking out what it is about this claim that causes the problem.

`lbry://@maynardjames#1/tncb#d`

**Comment by tzarebczan** [comment] 2019-11-17 16:54
Thanks for filing, this is a duplicate of https://github.com/lbryio/lbry-desktop/issues/3205 ( there's also an SDK side issue filed)

**Closed by tzarebczan** 2019-11-17 16:54 UTC
Labels: type: bug
