### ISSUE TITLE
"Enter Reward Code" doesn't accept Enter Key to trigger Redeem

### ISSUE THREAD

**Issue by julianschacher** [lbryio/lbry-desktop#2152] opened 2018-12-24 02:52 UTC
### Steps to Reproduce
1. Go to LBRY -> Wallet -> Rewards -> Custom Code -> Enter Code
2. Enter a code
3. Press the enter key

### Expected Behaviour
This should do the same as clicking the "Redeem"-Button.

### Actual Behaviour
Nothing happens.

## System Configuration

- LBRY Daemon version: 0.30.1
- LBRY App version: 0.26.1
- LBRY Installation ID: 9VS5gCQN19VnWvMapaPXd7v4oN7fRTZgExbKeKztv1q57hwC2bWZYKiywh6V4s5PkN
- Operating system: Mac OS 18.2.0

## Screenshots

*This is the UI element this issue is about:*
<img width="1748" alt="screenshot 2018-12-24 at 03 48 10_lbry_enter_reward_code" src="https://user-images.githubusercontent.com/26492670/50389799-f7469980-072e-11e9-8fc0-39069d5f05c0.png">

**Comment by seanyesmunt** [comment] 2018-12-24 02:55
Thanks for the issue @julianschacher !

This is an issue with all modals (I think the only other one is with email verification)

I think the issue is that the `button type="submit"` is not inside of these form elements.

**Comment by tzarebczan** [comment] 2018-12-27 20:21
@julianschacher, thanks for opening this issue - great suggestion! Can we send you [LBC in appreciation](https://lbry.io/faq/appreciation) for filling this out?

**Comment by seanyesmunt** [comment] 2019-02-12 18:56
Will be fixed in https://github.com/lbryio/lbry-desktop/pull/2279

**Comment by julianschacher** [comment] 2019-02-16 18:02
@seanyesmunt Awesome, thank you for your work!
@tzarebczan Thanks for the offer, but I don't think I deserve LBC for opening issue, which isn't a critical bug or something very special.

**Closed** 2019-02-16 18:04 UTC
Labels: good first issue, help wanted, type: bug

**Comment by seanyesmunt** [comment] 2019-02-16 18:05
@julianschacher Everything helps! It was helpful to have this issue created. It allowed us to track and prioritize it. Not sure when we would have fixed this if didn't create the issue!

**Comment by julianschacher** [comment] 2019-02-16 18:10
@seanyesmunt I agree, creating issues is super useful.
But for me (as a developer?) it's something natural to do, just because I want the project/product I use to improve. And if everyone lives with this mindset, you get payed by others reporting issues in projects you work on yourself.
I appreciate the gesture tho and I think it motivates people in general to report issues they find.

**Comment by seanyesmunt** [comment] 2019-02-16 18:12
I understand where you are coming from. Hope to see you around 🙂
