### ISSUE TITLE
No tray icon in Arch Linux

### ISSUE THREAD

**Issue by MR4Y** [lbryio/lbry-desktop#740] opened 2017-11-14 13:52 UTC
Title explains the issue.

### Steps to reproduce
1. Install lbry-app-bin from AUR
2. Open LBRY

### Expected behaviour
Much like every other Electron app, if the app has a tray icon, it should appear in the tray when the application opens.

### Actual behaviour
No tray icon shows up. Closing the app shuts down the daemon and closes the app.

## System Configuration
- LBRY Daemon version: 0.18.0
- LBRY App version: 0.18.0
- LBRY Installation ID: 2EASrt7xbwv2k7qwJkeSDjvrTJFPV6mZ9sgHUEA25YCuHh396Jo63tkhKTjjMp12H2
- Operating system: Linux (Linux-4.13.12-1-ARCH-x86_64-with-glibc2.3.4)

## Anything Else
Tested using XFCE

**Comment by tzarebczan** [comment] 2017-11-14 17:53
Thanks for the issue @MR4Y ! Sent you a couple LBC on Discord for filing this, it's a good find.

**Comment by hackrush01** [comment] 2017-11-14 18:48
Right now, in Linux, only Debian systems are supported.

Could you please post the output of the following command:
`pacman -Qi libappindicator1`. I could probably use the info to add tray
icon support in arch Linux systems.


-Regards
-Amit Tulshyan

On Nov 14, 2017 11:23 PM, "Thomas Zarebczan" <notifications@github.com>
wrote:

Thanks for the issue @MR4Y <https://github.com/mr4y> ! Sent you a couple
LBC on Discord for filing this, it's a good find.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lbryio/lbry-app/issues/740#issuecomment-344341912>, or mute
the thread

**Comment by MR4Y** [comment] 2017-11-14 19:25
Output:
```error: package 'libappindicator1' was not found```

**Comment by MR4Y** [comment] 2017-11-17 12:03
Updated lbry-app-bin to 0.18.2-1. Still no tray icon.

**Comment by tzarebczan** [comment] 2017-11-17 12:38
18.2 was a patch release which fixed a specific new user issue, nothing else was changed.

**Comment by kauffj** [comment] 2017-11-17 13:42
@MR4Y I believe Electron only supports tray icons in Linux distributions that support `libappindicator1`.

**Comment by MR4Y** [comment] 2017-11-25 11:03
Both Discord AUR buids have tray icons.

**Comment by etisdew** [comment] 2017-11-26 19:30
Off-topic: I would like to request any information you have regards to building to Arch for a proposal of addition to the instructions if able to resolve this. @MR4Y can we PM on discord?

**Comment by MR4Y** [comment] 2017-11-26 19:43
Yes.

**Comment by etisdew** [comment] 2017-11-26 19:49
@etisdew sorry, not sure which MR you are >_<

**Comment by kauffj** [comment] 2017-11-27 14:31
@etisdew @MR4Y as far as I know, Electron tray icons will only display if `libappindiactor1` is available. See:

- https://github.com/webtorrent/webtorrent-desktop/issues/383
- https://github.com/electron-userland/electron-builder/issues/375

Can you guys clarify this issue? Is it:

1. You have libappindiactor1 installed, but it doesn't work.
2. You do not have libappindiactor1 installed, and the LBRY install process didn't try to install it.
3. You do not have libappindaictor1 installed, the LBRY app tried to install it, but it's not available on your system.

If it's 1, we ought to try to debug it a bit further than open with Electron. If it's 2, we can look to modify the set up process. If it's 3, I'm not sure there's much we can do.

**Comment by hackrush01** [comment] 2017-11-27 15:06
OK so I got some time to look at the issue, and this is my diagnosis.
1) libappindicator1 indicator is not installed in the system (`pacman -Qi
libappindicator1`  returned negative).
2) Also the app explicitly checks for libappindicator1 in Debian based
systems(https://github.com/lbryio/lbry-app/blob/master/app/main.js#L522)
3) We install dependencies for debian(
https://github.com/lbryio/lbry-app/blob/master/package.json#L56), which I
think would need to be changed to support arch, fedora etc. systems.
4) We cannot remove the check completely because other quitting
functionality depends on this. We would need to include custom checks for
different systems.

**Comment by MR4Y** [comment] 2017-11-28 12:02
@kauffj As I explained earlier all builds of Discord have tray icons. None of them require libappindicator1.

**Comment by vv181** [comment] 2019-07-07 18:08
Trying to reproduce the issues, and it's not applied to the latest version. The tray icon is showing up as expected. I guess just close the issues, or did miss something here?

**Comment by tzarebczan** [comment] 2019-07-07 18:11
Woohoo, we may have fixed it up some other icon changes we made. Closing... Thanks @vv181

**Closed by tzarebczan** 2019-07-07 18:11 UTC
Labels: hacktoberfest, help wanted, level: 1, type: bug
