### ISSUE TITLE
Display of movie items is not correct when remove it after download movie.

### ISSUE THREAD

**Issue by namujan78** [lbryio/lbry-desktop#1474] opened 2018-05-11 08:32 UTC
## The Issue
Display of movie items is not correct when remove it after download movie.

### Steps to Reproduce
1. Go to any movie and remember it (ex MOVIE_03)
2. Click DOWNLOAD
3. Wait until there is some download progress (10%, 20%... COMPLETE)
4. Click REMOVE button
5. Tick on check box: Delete this file from my computer
6. Click REMOVE button to confirm remove

### Expected Behaviour
Go back to home page, and confirm the MOVIE_03. It should keep as same as original, there no icon of folder (mean You have a copy of this file), and when go to the MOVIE_03, you will need to click download or play again to have a copy of it.
And the movie is deleted.

### Actual Behaviour
Go back to home page, and confirm the MOVIE_03: You will see the icon of Folder (mean You have a copy of this file).
When click on it, it display xx% COMPLETE and REMOVE button.
But the movie is deleted.

### Suggested Solutions
N/A

## System Configuration
- LBRY Daemon version: 0.19.3
- LBRY App version: 0.21.4
- LBRY Installation ID: N/A
- Operating system: Windows 10

## Anything Else
N/A

## Screenshots
N/A

**Comment by tzarebczan** [comment] 2018-05-14 13:47
@namujan78 thanks for filing, this is most likely a timing issue related to https://github.com/lbryio/lbry/issues/1199 . Not much we can do about it on the app side for now, but will keep this issue open for tracking.

**Comment by tzarebczan** [comment] 2018-07-11 14:50
@namujan78 can you check to see if you can still reproduce this on the latest version? The new daemon should handle deletions better. Also, give it a few seconds after deleting before going back into the claim.

**Comment by namujan78** [comment] 2018-07-14 10:01
@tzarebczan It is not fixed, still same problem.

App | 0.22.2
Daemon (lbrynet) | 0.20.3
Wallet (lbryum) | 3.2.3

**Comment by namujan78** [comment] 2018-07-18 07:46
Happen with lbry://aggretsuko-a-cartoon-for-children-ages#66070156e7c93df52122b4359361e3424818b4c4
Frequency: 1/5

It’s quite hard to happen. Thanks.

**Comment by tzarebczan** [comment] 2018-08-10 13:38
Closing because it's a small timing issue between the app and daemon. Don't think it's a typical use case to delete the file and quickly go back to the file page.  As the daemon performance improves we should see less of this.

**Closed** 2018-08-10 13:39 UTC
Labels: area: ux, protocol dependent, type: bug
