### ISSUE TITLE
LBRY associates itself with html files on GNU/Linux without asking

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#5577] opened 2021-02-24 09:55 UTC
**Bug**

**To Reproduce**
"Each time when I start LBRY it sets HTML file
association to itself. I really don't want to open HTML files on my
computer with LBRY. This behavior is annoying."

**System Configuration**
- Operating system: Debian 10 and Debian 11
- Latest app from Deb file

**Additional context**
Reported by user via email

**Comment by infinite-persistence** [comment] 2021-02-25 02:14
Duplicate of #4729

**Closed** 2021-02-25 03:48 UTC
Labels: type: bug
