### ISSUE TITLE
"Open LBRY" does not restore to the last size

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-desktop#2397] opened 2019-03-29 20:45 UTC
I finally found what's causing this nuisance, minimizing then using "Open LBRY" from the tray icon changes the window size.
Happens on Windows, have not checked other OS's for similar.

**Comment by tzarebczan** [comment] 2019-03-29 20:48
Duplicate of https://github.com/lbryio/lbry-desktop/issues/1199 ?

**Comment by skhameneh** [comment] 2019-03-29 20:51
#1199 needs to be prioritized, a year is too long

**Closed** 2019-03-29 20:51 UTC
