### ISSUE TITLE
https://lbry.tv/@çokkomik - url won't load, too many redirects

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3464] opened 2020-01-09 16:16 UTC
This page isn’t workinglbry.tv redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by Yamboy1** [comment] 2020-01-13 07:53
Can't reproduce. Just says `There's nothing available at this location.`

**Comment by tzarebczan** [comment] 2020-01-13 14:12
He deleted it, but you can try creating the same channel name

**Comment by infinite-persistence** [comment] 2020-06-28 06:48
Can't reproduce with today's lbry.tv.  Seems to load ok.

**Comment by seanyesmunt** [comment] 2020-06-29 13:54
Seems to work for me too. Closing this.

**Closed by seanyesmunt** 2020-06-29 13:54 UTC
Labels: type: bug
