### ISSUE TITLE
Create "You must wait until thumbnail finishes uploading" message

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry-desktop#1821] opened 2018-07-25 22:17 UTC
I have been loving the new thumbnail upload feature!

However, it's possible that users will attempt to click 'Publish' before their thumbnail is done uploading to spee.ch.

In this case, we should have a message similar to "You must agree to terms and service" that lets them know that they can't publish without the thumbnail being published. 
![image](https://user-images.githubusercontent.com/38798392/43230510-857390d4-9036-11e8-8d7c-a5542e581f7e.png)

I think it makes the most sense if this message only pops up AFTER they click on agreeing to the terms and services. This way they don't see two messages at once saying "You must..." (we don't want to seem too demanding).

This also makes it so that they never see the message until they're actually ready to publish and the thumbnail upload is the only thing preventing them from it.

**Comment by tzarebczan** [comment] 2018-07-25 22:21
I was aware of this but didn't file because once the new wallet is inplemented, the response time should be a couple seconds.

Let's keep open until it's confirmed.

**Comment by jamesbiller** [comment] 2018-07-25 22:22
You mean it will only take a couple of seconds to upload the thumbnail?

**Comment by tzarebczan** [comment] 2018-07-25 22:23
Yes, sorry for not being clearer.

**Comment by tzarebczan** [comment] 2018-07-26 14:35
Agreed, we should implement this regardless. I may take a stab at it this weekend, shouldn't be too difficult.

**Comment by tzarebczan** [comment] 2018-08-14 14:59
Closed via https://github.com/lbryio/lbry-desktop/pull/1867

**Closed by tzarebczan** 2018-08-14 14:59 UTC
Labels: area: creator, good first issue, help wanted, level: 2, type: improvement
