### ISSUE TITLE
Embeds break on some URLs

### ISSUE THREAD

**Issue by kcseb** [lbryio/lbry-desktop#5213] opened 2020-12-19 01:09 UTC
**Bug**
When playing back a video from a Twitter embed, it some times breaks.

**To Reproduce**
Embed a video on Twitter (https://twitter.com/kcsebby/status/1340086993330581505)
Playback the video within that Twitter embed. 
See error.

**Expected behavior**
Should playback without showing the search button, hamburger menu, etc. 

**Screenshots**
![img](http://0x69.pw/i/225l6.png)

**Additional context**
Upon refresh, and second attempt at playback, the issue went away. Was able to replicate it again by refreshing a few more times.

**Comment by tzarebczan** [comment] 2020-12-19 01:13
Thanks for filing ,def a strange one! We've seen it break with some special characters before, but not the case here. We'll take a look.

**Comment by seanyesmunt** [comment] 2020-12-19 02:17
@kcseb What OS/browser are you using?

**Comment by kcseb** [comment] 2020-12-19 03:06
Windows 10 - Firefox 83.0 (x86_64)

**Comment by kauffj** [comment] 2020-12-22 18:19
Broken one on this page https://lemediaen442.fr/a-quoi-ressembleront-les-emplois-de-demain-selon-le-forum-economique-mondial/

**Comment by tzarebczan** [comment] 2020-12-28 18:42
This should be fixed now with a hotpatch from Sean.

**Comment by ehquionest** [comment] 2020-12-29 10:43
The issue is actually worst, no movies are showing up on theirthe link given by @kauffj above

**Comment by kauffj** [comment] 2020-12-29 14:53
@seanyesmunt embed fix was incomplete. It fixed most of them, but this one is now entirely broken:

https://lemediaen442.fr/a-quoi-ressembleront-les-emplois-de-demain-selon-le-forum-economique-mondial/

**Comment by tzarebczan** [comment] 2020-12-29 17:58
In firefox, I see (also happens in other browsers, but works there)  ```Uncaught TypeError: $ is not a function
    <anonymous> https://lemediaen442.fr/a-quoi-ressembleront-les-emplois-de-demain-selon-le-forum-economique-mondial/:1029
a-quoi-ressembleront-les-emplois-d```

Seems to work fine in Opera/Chrome/Brave here.

**Comment by ehquionest** [comment] 2020-12-29 18:57
sorry I am not a developper, just publisher... If I understood well, something in the link is not working properly?

**Comment by tzarebczan** [comment] 2021-01-04 21:47
Is it still broken for you? Can you show a screenshot of what it looks like? Also, if you can, press ctrl-shift-I to bring up the side bar, go to the console tab, then refresh and take a screenshot of that.

**Comment by kcseb** [comment] 2021-01-04 23:04
![img](http://0x69.pw/i/ceoe7.png)
![img](http://0x69.pw/i/4a6xk.png)

**Comment by tzarebczan** [comment] 2021-01-05 01:38
Sorry, I was replying to the other user having the issue on his site! I think we fixed most cases.

**Comment by ehquionest** [comment] 2021-01-10 07:54
"Content not found" here for me : https://lemediaen442.fr/allemagne-il-est-statistiquement-tres-probable-que-les-gens-ayant-ete-vaccines-meurent/

**Comment by ehquionest** [comment] 2021-01-17 12:07
We found the problem with this video embeded on the webpage mentionned above. The video URL was https://odysee.com/@TraductionEn442:a/Warning_Head_of_Gov't_Health_Agency_Admits_in_Advance_People_VOSTFR:8 and the apostrophe in the URL (Gov't) was breaking the embeded code not showing then the video.

**Comment by tzarebczan** [comment] 2021-01-17 20:15
Glad you found that, the share urls for those should be fixed soon.

**Closed** 2021-01-25 19:19 UTC
Labels: consider soon, type: bug
