### ISSUE TITLE
Remove channel from your list when it has been deleted

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-desktop#3443] opened 2020-01-04 18:46 UTC
**Is your feature request related to a problem? Please describe.**
If you have a channel that you have followed in the past but that channel no longer exists there is no way to unfollow it.

**Describe the solution you'd like**
Either - for all followers of a channel to be removed from following it automatically when the channel is deleted or when you click on the channel name on the right side a popup or overlay gives the warning that the channel no longer exists and the an unfollow button.

**Describe alternatives you've considered**
The alternatives are listed above - method 1 is better but more time consuming than method 2.

**Additional context**
None

**Comment by tzarebczan** [comment] 2020-01-04 18:56
Thanks for the issue, duplicate of https://github.com/lbryio/lbry-desktop/issues/2595

**Closed by tzarebczan** 2020-01-04 18:56 UTC
Labels: type: new feature

**Comment by auber262** [comment] 2020-01-04 19:15
Sorry, Tom. I didn't pick that one up despite a word search and mega paginated scroll back the list.
