### ISSUE TITLE
Notification toggling on following

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#4780] opened 2020-09-21 19:37 UTC
https://github.com/lbryio/internal-apis/issues/1104

**Comment by kauffj** [comment] 2020-09-21 19:40
Also get anything else from Mark or ask Mark to do anything else to make these work fully

**Comment by tzarebczan** [comment] 2020-09-28 16:03
Duplicate of https://github.com/lbryio/lbry-desktop/issues/4762

**Closed by tzarebczan** 2020-09-28 16:03 UTC
