### ISSUE TITLE
GDR as a country

### ISSUE THREAD

**Issue by RubenKelevra** [lbryio/lbry-desktop#5594] opened 2021-02-28 12:43 UTC
**Bug**
When should select a country in the LBC buy page it shows the "german democratic republic" as an option.

Kind of hilarious since it doesn't exist anymore for like 32 years.

**Screenshots**
![Screenshot_20210228_134045-1](https://user-images.githubusercontent.com/614929/109418851-b3184900-79ca-11eb-94f2-d3e9e9e5b3b8.png)

- LBRY version: 52878efae from git
- Operating system: Linux

**Additional context**
https://en.wikipedia.org/wiki/East_Germany

**Comment by kauffj** [comment] 2021-03-01 20:24
duplicate of #5397

**Closed by kauffj** 2021-03-01 20:24 UTC
Labels: type: bug
