### ISSUE TITLE
Lbry desktop I18nMessage links in French language at Experimental Settings card are broken.

### ISSUE THREAD

**Issue by netapau** [lbryio/lbry-desktop#3752] opened 2020-02-26 15:18 UTC
**Bug**
This displays: 
Semblable aux astuces, prend en charge l'aide __%d iscovery_link%__ mais la LBC est renvoyée dans votre portefeuille si elle est révoquée. Les deux aident également à sécuriser __votre% vanity_names_link%.__

**Expected behavior** (in french but with good links)
This will add a Support button along side tipping. Similar to tips, supports help [discovery](https://lbry.com/faq/trending) but the LBC is returned to your wallet if revoked. Both also help secure your [vanity](https://lbry.com/faq/naming) names.

see : https://github.com/lbryio/lbry-desktop/blob/da15eec31162c96e11d54332f9b4f874a2ee1a42/ui/page/settings/view.jsx#L627

1. Go to 'Settings'
2. Click on 'Select French language'
3. Scroll down to 'Experimental Settings Card'
4. See error (no good links)

**System Configuration**
- LBRY Daemon version: Daemon (lbrynet) | 0.61.0
- LBRY App version: Desktop 0.43.2
- LBRY Installation ID: 7j48tYsDJdCQgdnRTW7wpCv9Wkoevg5Ug6hvKPRWztqpixjjC4fNPaSxeVjpZbywjB
- Operating system:  Debian Linux 

**Additional context**
See the translation file.

**Comment by tzarebczan** [comment] 2020-02-26 17:21
Thank you for filing the issue! Can we show you some [appreciation](https://lbry.com/faq/appreciation)?

**Comment by netapau** [comment] 2020-02-26 17:45
Thanks, I hope it'll be usefull! :)

**Comment by kauffj** [comment] 2020-02-26 19:19
This issue is almost certainly due to a mis-formed string in Transifex. Unfortunately, we do not do any validation on these, so if someone typos or mis-copies interpolated strings the result can look pretty bad.

@tzarebczan or @jsigwart you can probably just log in to Transifex and adjust this, then fix will be live in 4-8 hours or whenever translation cache resets.

**Comment by netapau** [comment] 2020-02-27 09:35
That is what I thought. I'm curious to see the fr translations I saw some that are still missing.

**Comment by kauffj** [comment] 2020-02-27 22:54
@netapau if you join chat.lbry.org and start speaking in French (or maybe asking someone to give you translator role/access), that's where most of the organization (generous term) happens.

**Comment by netapau** [comment] 2020-02-28 15:27
Thanks for your advice @kauffj, I'll go there to see.

**Comment by jsigwart** [comment] 2020-03-04 18:47
This is what I'm seeing - not sure why these strings aren't translating into French. I checked the strings on transifex, and they appear to have the correct variable syntax.

<img width="975" alt="Screen Shot 2020-03-04 at 10 44 19 AM" src="https://user-images.githubusercontent.com/1363664/75912009-5872fe00-5e05-11ea-8822-ac4fb4970ef5.png">

**Comment by netapau** [comment] 2020-03-25 22:22
@jsigwart As you can see on line 634 the text is hard coded. So that doesn't take into account the translations.

**Comment by netapau** [comment] 2020-03-30 18:44
I did some tests in the Component "I18nMessage" because the problem lies only in these 3 cards:
* Wallet Security
* Experimental Transcoding
* Experimental Settings
According to the regexp we can have different results, it is also possible that there were new strings of translated.
It is certainly glossolalia. ;)
![Issue_3752_2](https://user-images.githubusercontent.com/701174/77949463-45016880-72c7-11ea-89ec-2b30141cde0f.png)

**Comment by kauffj** [comment] 2020-04-27 19:08
I closed #3928 because I think it is papering over an issue rather than understanding it. Do we have a clue on where the translations get mangled? On the way into Transifex, the way out, somewhere in i18n pipeline?

**Comment by infinite-persistence** [comment] 2020-05-27 18:06
In retrospec, I believe the issue is now fixed through https://github.com/lbryio/lbry-desktop/pull/4238.

**Closed** 2020-10-12 14:28 UTC
Labels: type: bug
