### ISSUE TITLE
CTRL + F

### ISSUE THREAD

**Issue by Aspie96** [lbryio/lbry-desktop#5887] opened 2021-04-14 12:37 UTC
CTRL + F on lbry.tv and odysee.com makes the video fullscreen instead of opening the search bar.

While also opening the search bar.

This is the typical sign of a bad design: altering the interpretation of user input. CTRL + F should only open the search bar

**Comment by infinite-persistence** [comment] 2021-04-14 13:41
`Close`
- Duplicate of #5865

**Closed by infinite-persistence** 2021-04-14 13:41 UTC
Labels: type: bug
