### ISSUE TITLE
search filters options partially broken

### ISSUE THREAD

**Issue by ramonschepers** [lbryio/lbry-desktop#3660] opened 2020-02-09 00:27 UTC
**Bug**
when i tried to use the search option a bit ago, i got to encounter a search bug with file types: it only being applied when i search cor content only, where it does not apply when i search for 'all' with for example only having selected media type "audio ", which still shows other types of content

**To Reproduce**
1) go to search on desktop app
2) search for a term (i used corona in my case)
3) open search filters
4) set searching for to everything (so not just users or content, but both)
5) set filetype to something else than all checkboxes (i tried only filtering by audio)
6) see the behaviour as linked in my screen from discord in screen1

**Expected behavior**
the search should be like the screen2 in screenshots, but the issue relies in the topmost option row it seems

some translation for the screenshots provided in case of needed:
zoeken naar = search for
bestanden / kanalen / alles = files / channels / everything(all)

**Screenshots**
screen1: 
https://cdn.discordapp.com/attachments/363087331475062785/675854179725606962/unknown.png
screen2: 
https://cdn.discordapp.com/attachments/363087331475062785/675854382755086366/unknown.png

**System Configuration**
deamon 0.54.1
app 0.41.0
os version: windows 10 x64

**Additional context**
small tip for a more stremlined search: making one filter section, thus merging the current 2 ones to: 
search for:
users, video, audio, pictures, text, other, downloads, your content.

yours, ramon.

**Comment by tzarebczan** [comment] 2020-02-10 17:33
Nice find, thank you! Looks like we don't pass them when the everything option is used, so they should be greyed out (when channels option is chosen also).

**Comment by tzarebczan** [comment] 2021-02-10 18:23
This recently came up as a source of confusion. We should hide or grey out those options on the search page.

**Comment by Ruk33** [comment] 2021-02-12 15:28
Thanks for the details in the bug report, it really helps! Will be working on it.

**Comment by Ruk33** [comment] 2021-02-12 16:12
Confirmed, the type parameter (`mediaType`) isn't being sent when using everything.

**Comment by Ruk33** [comment] 2021-02-12 17:21
There we go https://github.com/lbryio/lbry-desktop/pull/5516. Regards.

**Comment by tzarebczan** [comment] 2021-05-27 17:55
This is now fixed.

**Closed by tzarebczan** 2021-05-27 17:55 UTC
Labels: type: bug
