### ISSUE TITLE
Previous Claim Info Shows on Pending After New Publish Then Displays as Unused Until Restart

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1666] opened 2018-06-21 10:10 UTC
The two **pending** items shown in this screenshot, show the **previous** claims prices (50 LBC and FREE), **not** the new set price for the new claim which is __**10 LBC**__ in this case.

![image](https://user-images.githubusercontent.com/29914179/41712715-928bf3b4-758e-11e8-9969-86d691f4f3ce.png)

Then after a few minutes, all the info disappeared and the cards said **Unused**, 

![image](https://user-images.githubusercontent.com/29914179/41712810-d37f7f30-758e-11e8-9c86-df6358de1d80.png)

Then after restarting and clearing the cache, they eventually displayed correctly with the correct info.

![image](https://user-images.githubusercontent.com/29914179/41712854-ed0acbbc-758e-11e8-87fd-ee773fd186b0.png)

**Comment by tzarebczan** [comment] 2018-06-21 12:03
Did you leave the screen at all during this process? I think this is something isolated to an edge case or your environment, I've had better luck with edits in the past but will try to confirm.

Does this reproduce each time?

**Comment by tzarebczan** [comment] 2018-06-21 12:42
Ah, old you meant original vanity URL you are trying to take over. 

Does the unused location thing happen each time also? Can't seem to reproduce that on my end. 

I do see the issue with price not showing during a pending publish correctly - sometimes it shows nothing (which is probably what it should show), sometimes it shows free (even though I set a price - this was during a takeover).

**Comment by Invariant-Change** [comment] 2018-06-21 12:46
Yes. Previous. I've updated the title to be more clear.

Just going to check the "unused" issue again.

**Comment by Invariant-Change** [comment] 2018-06-21 12:55
"**Unused**" did not happen on this occasion. I will report back if I see again. Pending was also a lot quicker to resolve. So maybe a temp network error, or something?

**Comment by tzarebczan** [comment] 2018-06-21 13:01
Pending is checked every 30 seconds, and depends on when the claim is confirmed in a block.

**Comment by Invariant-Change** [comment] 2018-06-21 13:23
Pending was pending for several minutes. I just timed. It took around 5 minutes to stop pending. However, it seems if you switch views and come back, the pending info resolves. So it seems like an app update info issue, not a blockchain issue.

**Comment by Invariant-Change** [comment] 2018-06-21 13:28
Sorry, I mistook "**checked every 30**" for "**updated every 30**". Ignore the last comment.

**Comment by alyssaoc** [comment] 2018-11-12 20:16
@tzarebczan Has this been fixed?

**Comment by tzarebczan** [comment] 2018-11-14 18:11
Looks like this is fixed on the latest RC, @Invariant-Change please re-open if you see it pop up again after we release the update.

**Closed by tzarebczan** 2018-11-14 18:11 UTC
Labels: area: app d, area: creator, area: ux, priority: medium, type: bug
