### ISSUE TITLE
[Feature] Allow users to control content based on community/LBRY driven tags

### ISSUE THREAD

**Issue by asddsaz** [lbryio/lbry-desktop#1957] opened 2018-09-12 18:24 UTC
**Feature**: An opt-in blocker for inappropriate content.

**Why**: Many other decentralized streaming services have lots of inappropriate content and I don't believe people would be wiling to adopt a platform without the ability to block it.

**How**? Similar to safe search for platforms like Google, DuckDuckGo, and SearX.
When the report button gets pressed it could ask for why they are reporting the content.
Currently I believe it just does copyright.

**Comment by tzarebczan** [comment] 2018-09-12 21:28
Thanks for creating this issue! 

This is mostly a duplicate of https://github.com/lbryio/lbry-desktop/issues/1001

We will be moving to a model where users can report other types of content outside of DMCA and then they'll be able to opt into LBRY/Community suggested tags. 

We'll keep this issue open to keep track of work required to allow users to opt in/out of tags.

**Comment by tzarebczan** [comment] 2019-03-16 22:41
Replaced by https://github.com/lbryio/lbry-desktop/issues/2309

**Closed by tzarebczan** 2019-03-16 22:41 UTC
Labels: area: app d, area: app e, area: internal, area: viewer, type: new feature
