### ISSUE TITLE
Match the full list of keyboard shortcuts that YouTube has

### ISSUE THREAD

**Issue by overseeing** [lbryio/lbry-desktop#5042] opened 2020-11-15 08:17 UTC
#### Issue Summary

Environment: Desktop (e.g. Firefox browser)

[It's great we now have](https://lbry.com/news/comm-2019-10#news) `m` for toggle mute, `f` to toggle full screen and`→` and `←` to jump 10 seconds.

But when when efficiently consuming educational content (similar to speed reading), instant speed up/slow down via the keyboard is a big need!

YouTube has <kbd>shift</kbd>-<kbd>,</kbd> (comma) and <kbd>shift</kbd>-<kbd>.</kbd> (period) to decrease / increase speed.

Reference: https://support.google.com/youtube/answer/7631406

In fact, many others are useful in that list, like period and comma to go to next/prev frame while video paused. I use `c` to often toggle subtitles to help understand something being said.

So how about add all the others that work in LBRY? Makes sense to match their shortcuts to help drive adoption?

**Comment by infinite-persistence** [comment] 2020-11-17 14:17
Duplicate of [1395 Keyboard shortcuts](https://github.com/lbryio/lbry-desktop/issues/1395)?

**Comment by overseeing** [comment] 2020-11-17 15:50
> Duplicate of [1395 Keyboard shortcuts](https://github.com/lbryio/lbry-desktop/issues/1395)?

Now that this was moved into a different repo than where I originally posted this - definitely! :)

**Comment by tzarebczan** [comment] 2020-11-23 03:20
Closing the dupe, thanks for filing anyway! We def need to make it clearer that these are available.

**Closed by tzarebczan** 2020-11-23 03:20 UTC
