### ISSUE TITLE
LBRY desktop auto-sets itself as default application for opening html files in Linux file managers like nemo after logout and login or a cold/warm boot

### ISSUE THREAD

**Issue by TonyThuitai** [lbryio/lbry-desktop#4729] opened 2020-09-04 08:34 UTC
**Bug**
When opening an HTML file in a Linux File Manager like nemo, LBRY is launched instead of the default browser or application set to open HTML files. The defaults can be reverted in an HTML file properties but after a logout and login or a cold/warm boot, LBRY desktop sets itself as the default application for opening HTML files. Reverting to the default browser only lasts as long as one's PC is on and is no logout has occurred.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and install the lbry-desktop deb package and install it in any Debian/Ubuntu based OS.
2. Login to lbry via the app. (I am not sure if this contributes to the cause of the bug).
3. Logout and log back in or perform a warm/cold boot.
4. Create an HTML file with sample HTML code and launch/open it in the File Manager or launch/open an available HTML file in a File Manager
5. If lbry-desktop is launched instead of the default browser, revert to the default browser via the file properties and launch the file.
6. Logout and log back in or perform a warm/cold boot.
7. Launch the HTML file in a File Manager.

**Expected behaviour**
The default browser or applications like editors or IDEs should be used to launch/open an HTML file instead of lbry-desktop which currently auto-sets itself as the default application for launching/opening an HTML file after a cold/warm boot or a logout and login.

**Screenshots**
Below are the screenshots of the default web browser set
![default apps](https://user-images.githubusercontent.com/64726924/92216671-46027b80-ee9f-11ea-9972-4b55f7b4f7d2.png)

and when right clicking an html file in nemo (Cinnamon DE File Manager) and opens with LBRY by default.
![lbry default](https://user-images.githubusercontent.com/64726924/92216687-4a2e9900-ee9f-11ea-9990-edb76b725109.png)

**System Configuration**

- LBRY Daemon version: 0.79.1
- LBRY App version: 0.47.2
- LBRY Installation ID: 5nMz3Kv8dG4XhXqzeWBNt4dnYMYQpbFhWEuMQnhgkQxBsVuSRHQCwfwqLvGn6ru34N
- Operating system: Linux Mint 20 Cinnamon (Ubuntu 20.04 Base)

Full output of: `curl 'http://localhost:5279' --data '{"method":"version"}'`:
`{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "X-Cinnamon",
    "distro": {
      "codename": "ulyana",
      "id": "linuxmint",
      "like": "ubuntu",
      "version": "20",
      "version_parts": {
        "build_number": "",
        "major": "20",
        "minor": ""
      }
    },
    "lbrynet_version": "0.79.1",
    "os_release": "5.4.0-45-generic",
    "os_system": "Linux",
    "platform": "Linux-5.4.0-45-generic-x86_64-with-LinuxMint-20-ulyana",
    "processor": "x86_64",
    "python_version": "3.7.8",
    "version": "0.79.1"
  }
}`

**Comment by tzarebczan** [comment] 2020-09-04 15:09
Thanks for opening the issue. This is a strange bug with the underlying packaging we're using but it's not supposed to happen in our case. Hope it's fixed once we upgrade some of these components, and if not, we'll have to dig into it more: https://github.com/signalapp/Signal-Desktop/issues/3602

**Comment by OdinVex** [comment] 2020-09-10 20:05
Same issue. So frustrating as a developer that I removed LBRY for now.

**Comment by TonyThuitai** [comment] 2020-09-11 06:44
Also removed lbry-desktop and will reinstall when the issue has been fixed

**Comment by tzarebczan** [comment] 2020-09-11 14:24
Thanks for the feedback guys, we'll take a closer look at this soon!

**Comment by TonyThuitai** [comment] 2020-10-15 07:23
Noted that Electron was upgraded to V9 in Version 0.48.1 but the issue is still not fixed

**Comment by OdinVex** [comment] 2020-10-15 08:10
I can confirm, it still sets as default, but other Electron apps do not do this.

**Comment by kauffj** [comment] 2021-02-04 22:50
@jessopb any thoughts on why this is still happening or if it can be fixed by updating dependencies?

**Comment by OdinVex** [comment] 2021-02-04 23:07
> @jessopb any thoughts on why this is still happening or if it can be fixed by updating dependencies?

Just my own reply, I fixed it by simply removing LBRY and set my file-associations back to what they were before LBRY. I prevented LBRY from violating my file-associations by simply never installing it again.

**Comment by tzarebczan** [comment] 2021-02-05 02:01
I looked into this 2 weeks ago and tried other things, and no luck. This is a bug on xdg-utils https://github.com/balena-io/etcher/issues/3374#issuecomment-739558436

**Comment by tzarebczan** [comment] 2021-02-05 02:04
We can remove the LBRY protocol association for now on Linux until it's fixed.

**Comment by JonFStr** [comment] 2021-02-06 22:02
I use the following work-around to prevent LBRY from becoming the default-handler:
I execute `sudo chattr +i ~/.config/mimeapps.list` when LBRY is currently not the default.
This prevents any changes to the defaults, but since mine don't change that often, I can manually do `sudo chattr -i ~/.config/mimeapps.list` to reverse it every time I want to change a default.
Simply removing the write permission to that file does not work for me, so I'm setting the immutable bit which is only changeable by root

**Closed** 2021-03-08 16:21 UTC
Labels: consider soon, type: bug
