### ISSUE TITLE
Ability to block tags

### ISSUE THREAD

**Issue by matthewadie** [lbryio/lbry-desktop#4119] opened 2020-05-02 13:58 UTC
**Is your feature request related to a problem? Please describe.**
There is a lot of content on LBRY that I'm interested in and a lot of content that I would rather not see.  I would like a more efficient and flexible way of blocking content.

**Describe the solution you'd like**
I would like to be able to block based on a Tags.  For example I'm interested in technology in general, but when I search for technology based videos in a general way I'm overloaded by videos about the blockchain.  I would like to be able to block all videos that have blockchain set as a tag...

**Describe alternatives you've considered**
I've been blocking channels, but that gets unruly, it's not very elegant, and some of the channels I'm blocking might produce some content that I'm interested in.

**Comment by tzarebczan** [comment] 2020-05-02 15:18
Thanks for filing, this is a duplicate of https://github.com/lbryio/lbry-desktop/issues/2727

Please do a quick search if you can before opening new issues, thank you.

**Closed by tzarebczan** 2020-05-02 15:18 UTC
Labels: type: new feature
