### ISSUE TITLE
Add Tip button to channel page

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2810] opened 2019-08-28 22:45 UTC
There is no tip button on the current channel page.

Block can be hidden behind a menu or given reduced prominence if helpful to make space.

**Comment by tzarebczan** [comment] 2019-08-28 22:48
Duplicate of https://github.com/lbryio/lbry-desktop/issues/1397

**Closed by tzarebczan** 2019-08-28 22:48 UTC
Labels: consider soon
