### ISSUE TITLE
Floating video player goes away when opening an image

### ISSUE THREAD

**Issue by eatdostacos** [lbryio/lbry-desktop#4122] opened 2020-05-04 01:36 UTC
**Bug**
When I am watching a video in the floating player and I click on a different video, it shows all the information and doesn't play the video unless I start it and have it going. When I click on an image, the floating player disappears and the image is shown as the normal page. I then lose the video and have to go back and find it again.
**To Reproduce**
1. Go watch a video
2. Click somewhere else to put it into floating mode
3. Open any LBRY file page that's an image
4. See the floating player disappear

**Expected behavior**
 The floating player should stay unless I click to close it when looking at an image. 
**System Configuration**

App | 0.45.1-rc.3
Daemon (lbrynet) | 0.70.0
Connected Email | (my email)
Reward Eligible | Yes
Platform | Windows (Windows-10-10.0.18362-SP0)
Installation ID | 5njFMTAHy19ia14btQaJV1v2CBTZJuoCunyfYNUVqK4im5hdARQMnAM45MzCk8wx6o

**Comment by tzarebczan** [comment] 2020-05-04 01:37
Thanks for filing, it's a duplicate of: https://github.com/lbryio/lbry-desktop/issues/3654

**Closed by tzarebczan** 2020-05-04 01:37 UTC
Labels: type: bug
